
require "xky.options"
require "xky.keymaps"
require "xky.plugins"
require "xky.colorscheme"
require "xky.cmp"
require "xky.lsp"
require "xky.treesitter"
require "xky.autopairs"
require "xky.gitsigns"
