
require "xky.impatient"
require "xky.options"
require "xky.keymaps"
require "xky.plugins"
require "xky.colorscheme"
require "xky.cmp"
require "xky.lsp"
require "xky.treesitter"
require "xky.autopairs"
require "xky.gitsigns"
require "xky.nvim-tree"
require "xky.bufferline"
require "xky.lualine"
require "xky.toggleterm"
require "xky.project"
require "xky.indentline"
